# Generated by Django 5.2.6 on 2025-10-30 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', max_length=10)),
                ('puntos', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='CalculoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('nivel_actividad', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=50)),
                ('calorias_diarias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasas', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo Nutricional',
                'verbose_name_plural': 'Cálculos Nutricionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('avatar', models.CharField(default='👤', max_length=10)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogroDesbloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueado', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro Desbloqueado',
                'verbose_name_plural': 'Logros Desbloqueados',
                'unique_together': {('user', 'logro')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion_id', models.CharField(max_length=50)),
                ('leccion_nombre', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('puntuacion', models.IntegerField(default=0)),
                ('intentos', models.IntegerField(default=0)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_aprendizaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Aprendizaje',
                'verbose_name_plural': 'Progreso de Aprendizaje',
                'unique_together': {('user', 'leccion_id')},
            },
        ),
        migrations.CreateModel(
            name='RecetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta_id', models.IntegerField()),
                ('receta_nombre', models.CharField(max_length=200)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta Favorita',
                'verbose_name_plural': 'Recetas Favoritas',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('user', 'receta_id')},
            },
        ),
    ]
